version: '3'

services:
  worker:
    container_name: 'worker'
    build:
      context: ./
      dockerfile: miner/Dockerfile
    environment:
      AWS_SERVER_PUBLIC_KEY: ${AWS_SERVER_PUBLIC_KEY}
      AWS_SERVER_SECRET_KEY: ${AWS_SERVER_SECRET_KEY}
