name: miner-build-deploy

on:
  push:
    paths:
      - 'miner/**'
      - 'configs/miner/**'
      - '.github/workflows/miner.yml'
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:

  trigger-job:
    runs-on: ubuntu-latest
    steps:

    - name: Login to Yandex Cloud Container Registry
      id: login-cr
      uses: yc-actions/yc-cr-login@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build, tag, and push image to Yandex Cloud Container Registry
      env:
        CR_REGISTRY: crpktc7jeim3h82e69hv
        CR_REPOSITORY: place-recognition-mining-worker
        IMAGE_TAG: ${{ github.sha }}
      run: |
        export DOCKER_IMAGE=cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
        docker build -t $DOCKER_IMAGE -f ./miner/Dockerfile .
        docker push $DOCKER_IMAGE

    - name: Deploy COI Instance Group
      id: deploy-coi
      uses: yc-actions/yc-coi-deploy-ig@v1
      env:
        CR_REGISTRY: crpktc7jeim3h82e69hv
        CR_REPOSITORY: place-recognition-mining-worker
        IMAGE_TAG: ${{ github.sha }}
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        folder-id: b1g6d9jrqmedvatmdu88
        ig-spec-path: './configs/miner/spec.yml'
        user-data-path: './configs/miner/user-data.yml'
        docker-compose-path: './docker-compose-miner.yml'
